hotel_warehouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 9000
      user: default
      password: "clickhouse_password"
      database: default
      schema: default
      threads: 4
      keepalives_idle: 0
      search_path: "default"
      cluster_mode: false
      verify: false
      secure: false
      retries: 1
      compression: ""

    prod:
      type: clickhouse
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      port: "{{ env_var('CLICKHOUSE_PORT') | as_number }}"
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      database: "{{ env_var('CLICKHOUSE_DATABASE') }}"
      schema: "{{ env_var('CLICKHOUSE_SCHEMA') }}"
      threads: 4
      keepalives_idle: 0
      search_path: "{{ env_var('CLICKHOUSE_SCHEMA') }}"
      cluster_mode: false
      verify: false
      secure: true
      retries: 1
      compression: ""

guestflow_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-primary
      port: 5432
      user: postgres
      password: postgres_password
      dbname: guestflow
      schema: analytics
